### ISSUE TITLE
Add a favicon to make the tab easier to distinguish

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/triage-center#34]
I pin this tab but since it doesn't have a favicon I get a generic favicon. A high resolution (ideally SVG) favicon should be provided.

**Comment by emceeaich** [comment]
Let me see what I can source for that. I may have some discretionary
budget.

**Comment by mozfreddyb** [comment]
How about this green bug being swiped away with a broom?
https://commons.wikimedia.org/wiki/File:Green_bug_and_broom.svg
