### ISSUE TITLE
Don't require tracking status flags on components that aren't triaged

### ISSUE THREAD

**Issue by ahal** [mozilla/triage-center#66]
First off, thanks for the great tool!

I'm the triage-owner of several components related to test and CI infrastructure. Things related to development processes that have zero impact on end users. As such, we almost never set the various "firefoxNN" tracking flags. Even if we do, I believe bugs in these components would be excluded from release manager queries anyway. Some examples:

Firefox Build System :: Lint and Formatting
Firefox Build System :: Try
Testing :: Mochitest
<all other test suite components>

As of the May 4th update (I think), [my dashboard](https://mozilla.github.io/triage-center/?component=Firefox+Build+System%3ALint+and+Formatting&component=Firefox+Build+System%3ATry&component=Testing%3ACPPUnitTest&component=Testing%3AMochitest) has started flagging bugs that don't have a `firefoxNN` value set as "needing attention".

It would be great if we could drop this requirement for "untriaged" components, or offer some way to configure certain components to not require these values. Otherwise I'll have to spend unnecessary time and bug mails setting these flags just to clear them from my triage queue.

Thanks in advance!

**Comment by emceeaich** [comment]
After an initial review of the updated triage rules, it's been decided that we'll not require status flags to be set for triage. 

This will be resolved in an upcoming PR.

**Comment by emceeaich** [comment]
Fixed by 3efdd40a36e0a7002985796926832989e8baf0c5
