### ISSUE TITLE
Consider showing enhancement and task bugs on the triage decision lists

### ISSUE THREAD

**Issue by Standard8** [mozilla/triage-center#70]
We were just using the triage center and comparing with our previous queries.

One thing we noticed was that only bugs marked as defects were listed under the triage decision needed.

We were wondering if it should include enhancement and task bugs. If a bug has been filed/categorised wrongly then triagers may not see it, or if an enhancement is really something we wouldn't do then we should address that when it is filed.

**Comment by globau** [comment]
Looks like this has already been fixed.
