### ISSUE TITLE
Allow triage for assigned bugs without activity

### ISSUE THREAD

**Issue by whimboo** [mozilla/triage-center#71]
In various components we have assigned bugs which haven't been taken care of for certain amount of time. It would be great to have those listed in the triage central, and that I don't need a custom query for that.

Maybe a time span of about 2 or 3 weeks since the last update might be a good choice?

**Comment by globau** [comment]
I've implemented this in Triage Center's replaced - [BugDash](https://bugdash.moz.tools/).

**Comment by whimboo** [comment]
Hurray! Thanks a lot!
