### ISSUE TITLE
"Attention Needed" includes bugs from component that is not selected

### ISSUE THREAD

**Issue by mjzffr** [mozilla/triage-center#73]
Here is an example: https://mozilla.github.io/triage-center/?component=Remote+Protocol%3APerformance&component=Testing%3AMarionette

The selected components are:
* Testing:Marionette
* Remote Protocol:Performance

The Attention Needed list then includes bugs from "Testing:Performance" even though that component is not selected.

So the filter is likely using combinations of all products with all components.

**Comment by globau** [comment]
Here's what the query should look like:

https://bugzilla.mozilla.org/buglist.cgi?o5=equals&f4=OP&f1=flagtypes.name&f6=component&query_format=advanced&v1=needinfo&v6=Marionette&o9=equals&j3=OR&o2=lessthan&f12=CP&o10=equals&f10=component&f3=OP&f2=delta_ts&f9=product&v5=Testing&f11=CP&v10=Performance&v2=14d&v9=Remote%20Protocol&f8=OP&o6=equals&o1=substring&f7=CP&resolution=---&f5=product

```
f1=flagtypes.name
o1=substring
v1=needinfo

f2=delta_ts
o2=lessthan
v2=14d

f3=OP
j3=OR

  f4=OP

    f5=product
    o5=equals
    v5=Testing

    f6=component
    o6=equals
    v6=Marionette

  f7=CP

  f8=OP

    f9=product
    o9=equals
    v9=Remote%20Protocol

    f10=component
    o10=equals
    v10=Performance

  f11=CP

f12=CP
```
