### ISSUE TITLE
Highlight bugs filed by new contributors

### ISSUE THREAD

**Issue by emceeaich** [mozilla/triage-center#78]
Identify the "filed by someone who isn't an active Mozillian" case for bugs to potentially prioritize in general since they could be new community members we'd get engaged.

This would mean filtering on the `editbugs` group and since that requires an API key from a user in that group to search, we can't do this without re-architecting the app. 

An alternative would be to add a field to the Bugzilla API indicating if the user who filed the bug is new at the time they filed the bug (the Show Bug page looks at the reporter's user object to decide if the `new` flare should be shown.)

**Comment by globau** [comment]
While nice to have, this would require too much work and/or API overhead to implement.
