### ISSUE TITLE
A list for triaged bugs that are longstanding without activity?

### ISSUE THREAD

**Issue by saschanaz** [mozilla/triage-center#83]
It could be helpful to clear some longstanding issues, what do you think?

**Comment by globau** [comment]
I see where you're coming from however I don't think this is useful for bug triage.

I'd prefer to keep this dashboard focused on bugs that need attention; just because a bug hasn't been updated in a while that doesn't necessarily mean it needs attention.

**Comment by saschanaz** [comment]
Hmm, I think this is still helpful for maintenance effectiveness. But I understand the reason, I'll fork this then.

**Comment by saschanaz** [comment]
So I adjusted things a bit to split it from "Attention Needed", and here's the current version: https://saschanaz.github.io/longstandings/?component=Core%3ADOM%3A+Content+Processes&component=Core%3ADOM%3A+File&component=Core%3ADOM%3A+postMessage&component=Core%3ADOM%3A+Push+Notifications&component=Core%3ADOM%3A+Service+Workers&component=Core%3ADOM%3A+Web+Payments&component=Core%3ADOM%3A+Workers&component=Core%3ASpelling+checker&component=Core%3AStorage%3A+Cache+API&component=Core%3AStorage%3A+IndexedDB&component=Core%3AStorage%3A+localStorage+%26+sessionStorage&component=Core%3AStorage%3A+Quota+Manager

In my team we think this will be helpful for maintenance, and I think my current version does not give too much distraction. I can definitely maintain my fork but I think this can be helpful for other teams. Could you give a second look if you have time?

**Comment by globau** [comment]
Thank you for putting more time against this; moving it to a dedicate tab is great, and addresses my core concern.  Happy to merge a PR that does that!

**Comment by saschanaz** [comment]
Hey @globau, I'd like to advertise this feature in dev-platform google groups, what do you think?

(I wonder whether dev-platform is the best place, as probably a fair amount of subscribers are not in Mozilla and never do triaging 🤔)

**Comment by globau** [comment]
#triage-and-tracking on Slack would be a better place.
