### ISSUE TITLE
Exclude needinfo from the autonag bot for deciding between "Triage decision needed" and "NEEDINFO > 14 days" tables

### ISSUE THREAD

**Issue by marco-c** [mozilla/triage-center#87]
A bug such as https://bugzilla.mozilla.org/show_bug.cgi?id=1647988 should show up in the "Triage decision needed" table rather than "NEEDINFO > 14 days".

**Comment by globau** [comment]
Marco and I spoke about this; instead of taking this route we went with a new section that just lists escalated issues.
