### ISSUE TITLE
Some components missing

### ISSUE THREAD

**Issue by gbrownmozilla** [mozilla/triage-center#88]
I've been using triage-center to triage release engineering bugs. Just recently (within the last couple of weeks?) I find the Components tab is missing all components in the Release Engineering product. Can we get those back?

**Comment by globau** [comment]
Ah, I wasn't aware the RelEng follows the same triage process as Firefox.

> Just recently (within the last couple of weeks?)

This change happened at the end of last week.

I'll add `Release Engineering` back to traige-center, as well as adding it to the list of products on https://github.com/mozilla-bteam/bmo/blob/268a7a7f7dd35d3b7b20b9dc5952f99a9b6667fe/extensions/BMO/lib/Data.pm#L171

You should join the `#triage-and-tracking` Slack channel 🙂

**Comment by gbrownmozilla** [comment]
Thanks! It's not an official RelEng process, but I certainly find triage-center useful.

**Comment by globau** [comment]
Ah; if it isn't an official RelEng process then I'd prefer to leave it out.

As we make changes to the Firefox triage process both Triage Center and Bugzilla will be updated when required.
This is especially important in Bugzilla as more customisations are made to make it easier for Firefox triage; this requires the list of products I referenced, and doubles as a list of products that officially follow the process.

A disconnect between Triage Center and Bugzilla will be problematic, especially with the upcoming redefinition of how we determine if a bug has been triaged.

I'll reach out to you on Slack to see if there's something we can do.
