### ISSUE TITLE
Bug search query targetting wrong version

### ISSUE THREAD

**Issue by valenting** [mozilla/triage-center#91]
I was using the triage center for [Necko triage](https://mozilla.github.io/triage-center/?component=Core%3ADOM%3A+Networking&component=Core%3ANetworking&component=Core%3ANetworking%3A+Cache&component=Core%3ANetworking%3A+Cookies&component=Core%3ANetworking%3A+DNS&component=Core%3ANetworking%3A+FTP&component=Core%3ANetworking%3A+File&component=Core%3ANetworking%3A+HTTP&component=Core%3ANetworking%3A+JAR&component=Core%3ANetworking%3A+WebSockets) and I noticed that the Regressions without status flags section is wrong. 

The title is
Regressions without status flags for Firefox 112 (2)
but the search query is for firefox110
[View as bug search](https://bugzilla.mozilla.org/buglist.cgi?query_format=advanced&resolution=---&keywords=regression&keywords_type=allwords&chfield=%5BBug+creation%5D&chfieldfrom=2023-01-16&chfieldto=Now&f1=OP&j1=OR&f2=cf_status_firefox110&o2=nowords&v2=affected%2Cunaffected%2Cfixed%2Cverified%2Cdisabled%2Cverified+disabled%2Cwontfix%2Cfix-optional&f3=cf_status_firefox111&o3=nowords&v3=affected%2Cunaffected%2Cfixed%2Cverified%2Cdisabled%2Cverified+disabled%2Cwontfix%2Cfix-optional&f4=CP&f8=priority&o8=nowords&v8=P4%2CP5&f9=OP&j9=OR&f10=OP&f11=product&o11=equals&v11=Core&f12=component&o12=equals&v12=DOM%3A+Networking&f13=CP&f14=OP&f15=product&o15=equals&v15=Core&f16=component&o16=equals&v16=Networking&f17=CP&f18=OP&f19=product&o19=equals&v19=Core&f20=component&o20=equals&v20=Networking%3A+Cache&f21=CP&f22=OP&f23=product&o23=equals&v23=Core&f24=component&o24=equals&v24=Networking%3A+Cookies&f25=CP&f26=OP&f27=product&o27=equals&v27=Core&f28=component&o28=equals&v28=Networking%3A+DNS&f29=CP&f30=OP&f31=product&o31=equals&v31=Core&f32=component&o32=equals&v32=Networking%3A+FTP&f33=CP&f34=OP&f35=product&o35=equals&v35=Core&f36=component&o36=equals&v36=Networking%3A+File&f37=CP&f38=OP&f39=product&o39=equals&v39=Core&f40=component&o40=equals&v40=Networking%3A+HTTP&f41=CP&f42=OP&f43=product&o43=equals&v43=Core&f44=component&o44=equals&v44=Networking%3A+JAR&f45=CP&f46=OP&f47=product&o47=equals&v47=Core&f48=component&o48=equals&v48=Networking%3A+WebSockets&f49=CP&f50=CP&include_fields=assigned_to%2Ccomponent%2Ccreation_time%2Ccreator%2Cflags%2Cid%2Ckeywords%2Cpriority%2Cproduct%2Cseverity%2Csummary%2Ctype)

The [Regressions that need a decision for Firefox 112 (none)](https://bugzilla.mozilla.org/buglist.cgi?query_format=advanced&resolution=---&keywords=regression&keywords_type=allwords&chfield=%5BBug+creation%5D&chfieldfrom=2023-01-16&chfieldto=Now&f1=cf_status_firefox111&o1=nowords&v1=affected%2Cunaffected%2Cfixed%2Cverified%2Cdisabled%2Cverified+disabled%2Cwontfix%2Cfix-optional&f2=OP&j2=OR&f3=OP&f4=product&o4=equals&v4=Core&f5=component&o5=equals&v5=DOM%3A+Networking&f6=CP&f7=OP&f8=product&o8=equals&v8=Core&f9=component&o9=equals&v9=Networking&f10=CP&f11=OP&f12=product&o12=equals&v12=Core&f13=component&o13=equals&v13=Networking%3A+Cache&f14=CP&f15=OP&f16=product&o16=equals&v16=Core&f17=component&o17=equals&v17=Networking%3A+Cookies&f18=CP&f19=OP&f20=product&o20=equals&v20=Core&f21=component&o21=equals&v21=Networking%3A+DNS&f22=CP&f23=OP&f24=product&o24=equals&v24=Core&f25=component&o25=equals&v25=Networking%3A+FTP&f26=CP&f27=OP&f28=product&o28=equals&v28=Core&f29=component&o29=equals&v29=Networking%3A+File&f30=CP&f31=OP&f32=product&o32=equals&v32=Core&f33=component&o33=equals&v33=Networking%3A+HTTP&f34=CP&f35=OP&f36=product&o36=equals&v36=Core&f37=component&o37=equals&v37=Networking%3A+JAR&f38=CP&f39=OP&f40=product&o40=equals&v40=Core&f41=component&o41=equals&v41=Networking%3A+WebSockets&f42=CP&f43=CP&include_fields=assigned_to%2Ccomponent%2Ccreation_time%2Ccreator%2Cflags%2Cid%2Ckeywords%2Cpriority%2Cproduct%2Cseverity%2Csummary%2Ctype) link also seems wrong, pointing to firefox111

**Comment by globau** [comment]
As the wording and logic has been as it is currently for quite some time I'm hesitant to touch it without fully understanding why there's an apparent disconnect between the title and the query.

I'll ask around and see if we can clarify the situation and hopefully improve the wording and/or query to match the intent.

**Comment by globau** [comment]
The bug queries are correct - it's reporting on regressions that were _discovered_ recently that we need a decision on before the next release.
But I agree the title is not clear; what I'll do is remove the version number - so it'll just say "Regressions that need a decision"/etc

**Comment by valenting** [comment]
I see. Thanks for that.
Is it also expected that Regressions without status flags for Firefox 112 was querying 111 and 110, while Regressions that need a decision for Firefox 112 was querying only 111?

**Comment by globau** [comment]
Sorry about the delays; as part of the rewrite of Triage-Center I've tweaked this buglist; it's now "Important Recent Regressions Without Decision", queries both beta and release versions, but is limited to S1 and S2 bugs only.
